Change conf.d processing order and add error handling

diff --git a/packages.d/_ALWAYS.fixup.add/usr/local/sbin/config_save b/packages.d/_ALWAYS.fixup.add/usr/local/sbin/config_save
--- a/packages.d/_ALWAYS.fixup.add/usr/local/sbin/config_save
+++ b/packages.d/_ALWAYS.fixup.add/usr/local/sbin/config_save
@@ -10,11 +10,23 @@ try_partition() {
 
     # Mount partition as read-write
     mount /dev/$1 /mnt
+    S=$?
+
+    if [ $S -ne 0 ]; then
+        echo "Error: mount /dev/$1 to /mnt failed"
+        return $S
+    fi
 
     # Find conf.d in root of partition and save current configurations in /etc
     if [ -d "/mnt/$CONFDIR" ]; then
         echo Saving configurations to /dev/$1: "/mnt/$CONFDIR/50-node-config-save.tar.gz"
         tar --create --gzip -f "/mnt/$CONFDIR/50-node-config-save.tar.gz" -C /etc .
+        S=$?
+
+        if [ $S -ne 0 ]; then
+            echo "Error: create /mnt/$CONFDIR/50-node-config-save.tar.gz from /etc to /dev/$1 failed"
+            return $S
+        fi
 
         # Set function return value to successful
         echo Configurations saved to /dev/$1: "/mnt/$CONFDIR/50-node-config-save.tar.gz"
@@ -23,6 +35,12 @@ try_partition() {
 
     # Unmount partition
     umount /mnt
+    S=$?
+
+    if [ $S -ne 0 ]; then
+        echo "Error: umount /dev/$1 from /mnt failed"
+        return $S
+    fi
 
     return $retval
 }
